export enum AgentDepartmentTypeEnum {
  SALES = 'SALES',
  LOGISTICS = 'LOGISTICS',
  MARKETING = 'MARKETING',
  CUSTOMER_SUPPORT = 'CUSTOMER_SUPPORT',
  FINANCE = 'FINANCE',
  OPERATIONS = 'OPERATIONS'
}