export enum InventoryItemTypeEnum {
  RAW_MATERIAL = 'RAW_MATERIAL',
  FINISHED_GOOD = 'FINISHED_GOOD',
  PACKAGING_MATERIAL = 'PACKAGING_MATERIAL',
  SPARE_PART = 'SPARE_PART',
  CONSUMABLE = 'CONSUMABLE'
}